<?php
// CRITICAL: Extend server processing limit to 5 minutes for full-length matrix analysis
set_time_limit(300);
require_once 'db.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_FILES['audio_file'])) {
    $file = $_FILES['audio_file'];
    
    $fileName = basename($file['name']);
    $fileType = strtoupper(pathinfo($fileName, PATHINFO_EXTENSION));
    $fileSizeStr = round($file['size'] / (1024 * 1024), 1) . ' MB';
    
    if ($fileType !== 'MP3' && $fileType !== 'WAV') {
        die("Error: Unsupported format. Only MP3 and WAV files are allowed.");
    }

    $uploadDir = 'uploads/';
    if (!is_dir($uploadDir)) { mkdir($uploadDir, 0777, true); }
    
    $uniqueFileName = time() . '_' . $fileName;
    $targetFilePath = $uploadDir . $uniqueFileName;

    if (move_uploaded_file($file['tmp_name'], $targetFilePath)) {
        
        $absolutePath = realpath($targetFilePath);
        $safePath = escapeshellarg($absolutePath);
        
        // =========================================================
        // DIRECT EXECUTABLE PATH ROUTING
        // =========================================================
        $launcherPath = 'C:\\Windows\\py.exe'; 
        
        // Wrap the path and arguments securely
        $cmd = escapeshellcmd($launcherPath) . " extract_features.py " . $safePath . " 2>&1";
        
        // Execute the full processing loop
        $aiJsonOutput = shell_exec($cmd);
        
        // Strictly isolate the text using string position splitting to drop background notices
        if (strpos($aiJsonOutput, '[AI_START]') !== false && strpos($aiJsonOutput, '[AI_END]') !== false) {
            $startPos = strpos($aiJsonOutput, '[AI_START]') + strlen('[AI_START]');
            $endPos = strpos($aiJsonOutput, '[AI_END]');
            $cleanJson = substr($aiJsonOutput, $startPos, $endPos - $startPos);
            $cleanJson = trim($cleanJson); // Strip any accidental hidden newlines or spaces
        } else {
            $cleanJson = trim($aiJsonOutput);
        }
        
        $aiResult = json_decode($cleanJson, true);
        
        if (!$aiResult || isset($aiResult['error'])) {
            die("AI Pipeline Calculation Timeout. Technical Details: " . ($cleanJson ?? 'Null string output response.'));
        }

        // =========================================================
        // DYNAMIC METADATA EXTRACTION
        // =========================================================
        $tempo = $aiResult['tempo'];
        $pitch = $aiResult['pitch'];
        $track_duration = $aiResult['duration'];
        $genre_id = $aiResult['genre_id'];
        $language_name = $aiResult['language_name'];
        $language_id = $aiResult['language_id'];
        $confidence = $aiResult['confidence'];
        $waveform = $aiResult['waveform_sample'];
        
        // Capture the live lyrics generated by our Python NLP process
        $lyricsText = $aiResult['lyrics'] ?? "Audio content indexed under target classroom coursework domain.";

        try {
            $pdo->beginTransaction();

            // Insert dynamic metadata into main AUDIO schema hub table
            $sqlAudio = "INSERT INTO AUDIO (file_name, file_type, file_size, duration, date_upload, file_path, user_id, genre_id, languange_id) 
                         VALUES (:file_name, :file_type, :file_size, :duration, :date_upload, :file_path, 1, :genre_id, :languange_id)";
            $stmtAudio = $pdo->prepare($sqlAudio);
            $stmtAudio->execute([
                ':file_name'   => $fileName,
                ':file_type'   => $fileType,
                ':file_size'   => $fileSizeStr,
                ':duration'    => $track_duration,
                ':date_upload' => date('Y-m-d'),
                ':file_path'   => $targetFilePath,
                ':genre_id'    => $genre_id,
                ':languange_id'=> $language_id
            ]);
            
            $newAudioId = $pdo->lastInsertId();

            // =========================================================
            // DYNAMICALLY SAVE THE NLP EXTRACTED LYRICS (TBR)
            // =========================================================
            $sqlTranscript = "INSERT INTO TRANSCRIPT (transcript_text, audio_id) VALUES (:text, :audio_id)";
            $stmtTranscript = $pdo->prepare($sqlTranscript);
            $stmtTranscript->execute([
                ':text'     => $lyricsText, 
                ':audio_id' => $newAudioId
            ]);

            // Save low-level content feature representations (CBR)
            $sqlFeature = "INSERT INTO AUDIO_FEATURE (tempo, pitch, rhythm, waveform_feature, spectrogram_feature, audio_id) 
                           VALUES (:tempo, :pitch, '4/4', :waveform, 'spectrograms/default.png', :audio_id)";
            $stmtFeature = $pdo->prepare($sqlFeature);
            $stmtFeature->execute([
                ':tempo'    => $tempo, 
                ':pitch'    => $pitch, 
                ':waveform' => $waveform, 
                ':audio_id' => $newAudioId
            ]);

            $pdo->commit();
            header("Location: detail.php?id=" . $newAudioId);
            exit();

        } catch (Exception $e) {
            $pdo->rollBack();
            die("Database Storage Error: " . $e->getMessage());
        }
    } else {
        die("Error moving file to uploads directory.");
    }
}
?>